apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration
  template:
    metadata:
      labels:
        app: expiration
    spec:
      containers:
        - name: expiration
          #gcloud image: us.gcr.io/ticketing-dev-300706/expiration
          image: mohammad1977/expiration
          env:
            - name: SERVICE_URI
              value: "/api/expiration"
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CUSTER_ID
              value: ticketing
            - name: REDIS_HOST
              value: expiration-redis-srv
